repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: test
        name: Test
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
